version: '3'
services:
  ms-review:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/reviews
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
