apiVersion: v1
kind: Pod
metadata:
  name: ms-sales-pod
spec:
  containers:
  - name: ms-sales-container
    image: #Falta agregar imagen en la razi del proyecto hay ejemplo de como hacerlo
    ports:
    - containerPort: 3000
    env:
    - name: DB_URI
      value: "mongodb://ms-sales-db:27017/sales-service"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-sales-service
spec:
  selector:
    app: ms-sales
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000