apiVersion: v1
kind: Pod
metadata:
  name: ms-reviews-db-pod
spec:
  containers:
  - name: ms-reviews-db-container
    image: mongo
    ports:
    - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ms-reviews-db-service
spec:
  selector:
    app: ms-reviews-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017