apiVersion: v1
kind: Pod
metadata:
  name: ms-reviews-pod
spec:
  containers:
  - name: ms-reviews-container
    image: isabela22/ms_reviews_server
    ports:
    - containerPort: 5000
    env:
    - name: MONGO_URI
      value: "mongodb://ms-reviews-db:27017/reviewsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-reviews-service
spec:
  selector:
    app: ms-reviews
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000