apiVersion: v1
kind: Pod
metadata:
  name: orchestrator-pod
spec:
  containers:
  - name: orchestrator-container
    image: <tu-imagen-de-orchestrator>
    ports:
    - containerPort: 4800
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: TCP
    port: 4800
    targetPort: 4800