apiVersion: v1
kind: Pod
metadata:
  name: ms-repairs-pod
spec:
  containers:
  - name: ms-repairs-container
    image: #Falta agregar imagen en la razi del proyecto hay ejemplo de como hacerlo
    ports:
    - containerPort: 3006
    env:
    - name: DB_HOST
      value: "ms_repairs_db"
    - name: DB_USER
      value: "root"
    - name: DB_PASSWORD
      value: "test"
    - name: DB_PORT
      value: "3306"
    - name: DB_DATABASE
      value: "msrepairs"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-repairs-service
spec:
  selector:
    app: ms-repairs
  ports:
  - protocol: TCP
    port: 3006
    targetPort: 3006